import type { TelemetrySnapshot } from './telemetry-collector.ts';

export interface CopilotResponse {
  commands: string[];
  explanation: string;
  model: string;
}

export interface DiagnosticFinding {
  metric: string;
  value: string;
  status: 'optimal' | 'warning' | 'critical';
  insight: string;
}

export interface DiagnosticReport {
  status: 'OPTIMAL' | 'ATTENTION' | 'CRITICAL';
  headline: string;
  overallScore: number; // 0 - 100
  keyFindings: DiagnosticFinding[];
  recommendations: string[];
  generatedAt: string;
  model: string;
}

export class GeminiService {
  private readonly apiKey: string | null;
  private readonly modelName: string = 'gemini-3.5-flash-lite';
  private readonly fallbackModel: string = 'gemini-2.5-flash-lite';

  constructor(apiKey?: string) {
    if (apiKey !== undefined) {
      this.apiKey = apiKey.trim().length > 0 ? apiKey.trim() : null;
    } else {
      this.apiKey = process.env.GEMINI_API_KEY || null;
    }
  }

  public isAvailable(): boolean {
    return !!this.apiKey && this.apiKey.length > 0;
  }

  /**
   * Translates a natural language user prompt into valid RadixKV RESP commands.
   */
  public async translateToRedisCommands(prompt: string): Promise<CopilotResponse> {
    if (!this.isAvailable()) {
      throw new Error('Gemini API key is not configured. Please set GEMINI_API_KEY.');
    }

    const systemPrompt = `You are the RadixKV AI Copilot. RadixKV is an in-memory Redis-compatible key-value store.
Supported commands are:
- PING [message]
- SET key value [EX seconds]
- GET key
- INCR key
- TTL key
- DEL key [key ...]
- QUIT

Given the user's natural language request, convert it into an array of one or more executable Redis commands.
Do not invent unsupported commands (like HSET, LPUSH, KEYS, MSET etc.). Use supported commands only.

RESPOND ONLY WITH A VALID JSON OBJECT MATCHING THIS EXACT SCHEMA:
{
  "commands": ["SET user:101 'Alice' EX 3600"],
  "explanation": "Creates user session with 1 hour expiration"
}
Do not wrap in any extra text or conversational chatter outside the JSON.`;

    const userContent = `User Request: "${prompt}"`;

    const result = await this.callGemini(systemPrompt, userContent);
    const parsed = this.cleanAndParseJson(result.text);

    return {
      commands: Array.isArray(parsed.commands) ? parsed.commands : [parsed.command || 'PING'],
      explanation: parsed.explanation || 'Command generated by Gemini AI Copilot.',
      model: result.modelUsed,
    };
  }

  /**
   * Analyzes live cluster telemetry data and returns health diagnostics and recommendations.
   */
  public async generateClusterDiagnostics(
    snapshot: TelemetrySnapshot,
    clusterInfo: { shardCount: number; tcpPort: number; telemetryPort: number; syntheticTraffic: boolean }
  ): Promise<DiagnosticReport> {
    if (!this.isAvailable()) {
      throw new Error('Gemini API key is not configured. Please set GEMINI_API_KEY.');
    }

    const systemPrompt = `You are a Principal Database Reliability Engineer specializing in in-memory distributed caches and Redis clusters.
Analyze the following real-time performance telemetry snapshot from RadixKV and produce an actionable health diagnosis.

RESPOND ONLY WITH A VALID JSON OBJECT MATCHING THIS EXACT SCHEMA:
{
  "status": "OPTIMAL" | "ATTENTION" | "CRITICAL",
  "headline": "Short 1-sentence executive summary of cluster health",
  "overallScore": 92,
  "keyFindings": [
    {
      "metric": "Throughput",
      "value": "780 ops/sec",
      "status": "optimal",
      "insight": "Consistent load distributed across all 8 worker shards."
    }
  ],
  "recommendations": [
    "Specific tuning recommendation 1",
    "Specific tuning recommendation 2"
  ]
}
Do not include any prose outside the JSON.`;

    const telemetryContext = {
      timestamp: new Date().toISOString(),
      clusterTopology: {
        shards: clusterInfo.shardCount,
        vnodesPerShard: 150,
        syntheticTrafficActive: clusterInfo.syntheticTraffic,
      },
      throughput: {
        currentOpsPerSec: snapshot.opsPerSec,
        totalOperations: snapshot.totalCommands,
        commandBreakdown: snapshot.commandBreakdown,
      },
      latencies: {
        p50Ms: snapshot.latencies.p50,
        p90Ms: snapshot.latencies.p90,
        p95Ms: snapshot.latencies.p95,
        p99Ms: snapshot.latencies.p99,
        avgMs: snapshot.latencies.avg,
      },
      cacheEfficiency: {
        hitMissRatio: snapshot.hitMissRatio,
        hits: snapshot.hitCount,
        misses: snapshot.missCount,
      },
      memory: {
        heapUsedMb: snapshot.memory.heapUsedMb,
        heapTotalMb: snapshot.memory.heapTotalMb,
        rssMb: snapshot.memory.rssMb,
      },
      shardBalance: snapshot.shardStats.map((s) => ({
        shard: s.shardId,
        keys: s.keyCount,
        expires: s.expiresCount,
        ops: s.totalOps,
      })),
    };

    const userContent = `Live Telemetry Data:\n${JSON.stringify(telemetryContext, null, 2)}`;

    const result = await this.callGemini(systemPrompt, userContent);
    const parsed = this.cleanAndParseJson(result.text);

    return {
      status: ['OPTIMAL', 'ATTENTION', 'CRITICAL'].includes(parsed.status) ? parsed.status : 'OPTIMAL',
      headline: parsed.headline || 'Cluster is performing within normal operational parameters.',
      overallScore: typeof parsed.overallScore === 'number' ? Math.min(100, Math.max(0, parsed.overallScore)) : 88,
      keyFindings: Array.isArray(parsed.keyFindings) ? parsed.keyFindings : [],
      recommendations: Array.isArray(parsed.recommendations) ? parsed.recommendations : [],
      generatedAt: new Date().toISOString(),
      model: result.modelUsed,
    };
  }

  /**
   * Internal HTTP caller for Gemini API with model fallback.
   */
  private async callGemini(
    systemInstruction: string,
    prompt: string
  ): Promise<{ text: string; modelUsed: string }> {
    const modelsToTry = [this.modelName, this.fallbackModel, 'gemini-flash-latest'];

    let lastError: Error | null = null;

    for (const model of modelsToTry) {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${this.apiKey}`;

      const payload = {
        contents: [
          {
            role: 'user',
            parts: [{ text: `${systemInstruction}\n\n${prompt}` }],
          },
        ],
        generationConfig: {
          temperature: 0.2,
          maxOutputTokens: 1024,
        },
      };

      try {
        const res = await fetch(url, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
          signal: AbortSignal.timeout(25_000),
        });

        if (res.ok) {
          const data = await res.json();
          const candidate = data.candidates?.[0];
          const text = candidate?.content?.parts?.[0]?.text;
          if (text) {
            return { text, modelUsed: model };
          }
        } else {
          const errData = await res.json().catch(() => ({}));
          lastError = new Error(errData.error?.message || `HTTP ${res.status}`);
          // If model is not found, continue to next model
          if (res.status === 404 || res.status === 503) {
            continue;
          }
          break;
        }
      } catch (err: any) {
        lastError = err;
      }
    }

    throw lastError || new Error('Failed to query Gemini API');
  }

  /**
   * Cleans potential markdown fences around JSON output and parses it.
   */
  private cleanAndParseJson(rawText: string): any {
    let text = rawText.trim();
    if (text.startsWith('```json')) {
      text = text.substring(7);
    } else if (text.startsWith('```')) {
      text = text.substring(3);
    }
    if (text.endsWith('```')) {
      text = text.substring(0, text.length - 3);
    }
    return JSON.parse(text.trim());
  }
}
